// <auto-generated />
namespace WebSiteProjectA.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AdminControl : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AdminControl));
        
        string IMigrationMetadata.Id
        {
            get { return "201606210649018_Admin-Control"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
